// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DriveFlow_CRM_API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260128120408_ExamFormLinkedToLicense")]
    partial class ExamFormLinkedToLicense
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DriveFlow_CRM_API.Models.Address", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AddressNumber")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("Postcode")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("StreetName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("AddressId");

                    b.HasIndex("CityId");

                    b.HasIndex("Postcode")
                        .IsUnique();

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("DriveFlow_CRM_API.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int?>("AutoSchoolId")
                        .HasColumnType("int");

                    b.Property<string>("Cnp")
                        .HasMaxLength(13)
                        .HasColumnType("varchar(13)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("AutoSchoolId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("DriveFlow_CRM_API.Models.ApplicationUserTeachingCategory", b =>
                {
                    b.Property<int>("ApplicationUserTeachingCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("TeachingCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("ApplicationUserTeachingCategoryId");

                    b.HasIndex("TeachingCategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("ApplicationUserTeachingCategories");
                });

            modelBuilder.Entity("DriveFlow_CRM_API.Models.Appointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<TimeSpan>("EndHour")
                        .HasColumnType("time(6)");

                    b.Property<int?>("FileId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("StartHour")
                        .HasColumnType("time(6)");

                    b.HasKey("AppointmentId");

                    b.HasIndex("FileId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("DriveFlow_CRM_API.Models.AutoSchool", b =>
                {
                    b.Property<int>("AutoSchoolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("WebSite")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("AutoSchoolId");

                    b.HasIndex("AddressId")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("AutoSchools");
                });

            modelBuilder.Entity("DriveFlow_CRM_API.Models.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CountyId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("CityId");

                    b.HasIndex("CountyId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("DriveFlow_CRM_API.Models.County", b =>
                {
                    b.Property<int>("CountyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("CountyId");

                    b.HasIndex("Abbreviation")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Counties");
                });

            modelBuilder.Entity("DriveFlow_CRM_API.Models.ExamForm", b =>
                {
                    b.Property<int>("FormId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("LicenseId")
                        .HasColumnType("int");

                    b.Property<int>("MaxPoints")
                        .HasColumnType("int");

                    b.HasKey("FormId");

                    b.HasIndex("LicenseId")
                        .IsUnique();

                    b.ToTable("ExamForms");
                });

            modelBuilder.Entity("DriveFlow_CRM_API.Models.ExamItem", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("FormId")
                        .HasColumnType("int");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<int>("PenaltyPoints")
                        .HasColumnType("int");

                    b.HasKey("ItemId");

                    b.HasIndex("FormId", "Description")
                        .IsUnique();

                    b.ToTable("ExamItems");
                });

            modelBuilder.Entity("DriveFlow_CRM_API.Models.File", b =>
                {
                    b.Property<int>("FileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("CriminalRecordExpiryDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("InstructorId")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("MedicalRecordExpiryDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ScholarshipStartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("TeachingCategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("FileId");

                    b.HasIndex("InstructorId");

                    b.HasIndex("StudentId");

                    b.HasIndex("TeachingCategoryId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("DriveFlow_CRM_API.Models.InstructorAvailability", b =>
                {
                    b.Property<int>("IntervalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<TimeSpan>("EndHour")
                        .HasColumnType("time(6)");

                    b.Property<string>("InstructorId")
                        .HasColumnType("varchar(255)");

                    b.Property<TimeSpan>("StartHour")
                        .HasColumnType("time(6)");

                    b.HasKey("IntervalId");

                    b.HasIndex("InstructorId");

                    b.ToTable("InstructorAvailabilities");
                });

            modelBuilder.Entity("DriveFlow_CRM_API.Models.License", b =>
                {
                    b.Property<int>("LicenseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)");

                    b.HasKey("LicenseId");

                    b.HasIndex("Type")
                        .IsUnique();

                    b.ToTable("Licenses");
                });

            modelBuilder.Entity("DriveFlow_CRM_API.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("FileId")
                        .HasColumnType("int");

                    b.Property<bool>("ScholarshipBasePayment")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("SessionsPayed")
                        .HasColumnType("int");

                    b.HasKey("PaymentId");

                    b.HasIndex("FileId")
                        .IsUnique();

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("DriveFlow_CRM_API.Models.Request", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("AutoSchoolId")
                        .HasColumnType("int");

                    b.Property<string>("DrivingCategory")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("RequestId");

                    b.HasIndex("AutoSchoolId");

                    b.HasIndex("RequestDate");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("DriveFlow_CRM_API.Models.SessionForm", b =>
                {
                    b.Property<int>("SessionFormId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FinalizedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("FormId")
                        .HasColumnType("int");

                    b.Property<string>("MistakesJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Result")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("TotalPoints")
                        .HasColumnType("int");

                    b.HasKey("SessionFormId");

                    b.HasIndex("AppointmentId")
                        .IsUnique();

                    b.HasIndex("FormId");

                    b.ToTable("SessionForms");
                });

            modelBuilder.Entity("DriveFlow_CRM_API.Models.TeachingCategory", b =>
                {
                    b.Property<int>("TeachingCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AutoSchoolId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<int?>("LicenseId")
                        .HasColumnType("int");

                    b.Property<int>("MinDrivingLessonsReq")
                        .HasColumnType("int");

                    b.Property<decimal>("ScholarshipPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("SessionCost")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("SessionDuration")
                        .HasColumnType("int");

                    b.HasKey("TeachingCategoryId");

                    b.HasIndex("LicenseId");

                    b.HasIndex("AutoSchoolId", "Code")
                        .IsUnique();

                    b.ToTable("TeachingCategories");
                });

            modelBuilder.Entity("DriveFlow_CRM_API.Models.Vehicle", b =>
                {
                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("AutoSchoolId")
                        .HasColumnType("int");

                    b.Property<string>("Brand")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Color")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<decimal?>("EngineSizeLiters")
                        .HasColumnType("decimal(3,1)");

                    b.Property<int?>("FuelType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("InsuranceExpiryDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ItpExpiryDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("LicenseId")
                        .HasColumnType("int");

                    b.Property<string>("LicensePlateNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Model")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("PowertrainType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RcaExpiryDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("TransmissionType")
                        .HasColumnType("int");

                    b.Property<int?>("YearOfProduction")
                        .HasColumnType("int");

                    b.HasKey("VehicleId");

                    b.HasIndex("AutoSchoolId");

                    b.HasIndex("LicenseId");

                    b.HasIndex("LicensePlateNumber")
                        .IsUnique();

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DriveFlow_CRM_API.Models.Address", b =>
                {
                    b.HasOne("DriveFlow_CRM_API.Models.City", "City")
                        .WithMany("Addresses")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("DriveFlow_CRM_API.Models.ApplicationUser", b =>
                {
                    b.HasOne("DriveFlow_CRM_API.Models.AutoSchool", "AutoSchool")
                        .WithMany("ApplicationUsers")
                        .HasForeignKey("AutoSchoolId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("AutoSchool");
                });

            modelBuilder.Entity("DriveFlow_CRM_API.Models.ApplicationUserTeachingCategory", b =>
                {
                    b.HasOne("DriveFlow_CRM_API.Models.TeachingCategory", "TeachingCategory")
                        .WithMany("ApplicationUserTeachingCategories")
                        .HasForeignKey("TeachingCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DriveFlow_CRM_API.Models.ApplicationUser", "User")
                        .WithMany("ApplicationUserTeachingCategories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TeachingCategory");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DriveFlow_CRM_API.Models.Appointment", b =>
                {
                    b.HasOne("DriveFlow_CRM_API.Models.File", "File")
                        .WithMany("Appointments")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("File");
                });

            modelBuilder.Entity("DriveFlow_CRM_API.Models.AutoSchool", b =>
                {
                    b.HasOne("DriveFlow_CRM_API.Models.Address", "Address")
                        .WithOne()
                        .HasForeignKey("DriveFlow_CRM_API.Models.AutoSchool", "AddressId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Address");
                });

            modelBuilder.Entity("DriveFlow_CRM_API.Models.City", b =>
                {
                    b.HasOne("DriveFlow_CRM_API.Models.County", "County")
                        .WithMany("Cities")
                        .HasForeignKey("CountyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("County");
                });

            modelBuilder.Entity("DriveFlow_CRM_API.Models.ExamForm", b =>
                {
                    b.HasOne("DriveFlow_CRM_API.Models.License", "License")
                        .WithOne("ExamForm")
                        .HasForeignKey("DriveFlow_CRM_API.Models.ExamForm", "LicenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("License");
                });

            modelBuilder.Entity("DriveFlow_CRM_API.Models.ExamItem", b =>
                {
                    b.HasOne("DriveFlow_CRM_API.Models.ExamForm", "ExamForm")
                        .WithMany("Items")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExamForm");
                });

            modelBuilder.Entity("DriveFlow_CRM_API.Models.File", b =>
                {
                    b.HasOne("DriveFlow_CRM_API.Models.ApplicationUser", "Instructor")
                        .WithMany("InstructorFiles")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DriveFlow_CRM_API.Models.ApplicationUser", "Student")
                        .WithMany("StudentFiles")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DriveFlow_CRM_API.Models.TeachingCategory", "TeachingCategory")
                        .WithMany("Files")
                        .HasForeignKey("TeachingCategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DriveFlow_CRM_API.Models.Vehicle", "Vehicle")
                        .WithMany("Files")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Instructor");

                    b.Navigation("Student");

                    b.Navigation("TeachingCategory");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("DriveFlow_CRM_API.Models.InstructorAvailability", b =>
                {
                    b.HasOne("DriveFlow_CRM_API.Models.ApplicationUser", "Instructor")
                        .WithMany("InstructorAvailabilities")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("DriveFlow_CRM_API.Models.Payment", b =>
                {
                    b.HasOne("DriveFlow_CRM_API.Models.File", "File")
                        .WithOne()
                        .HasForeignKey("DriveFlow_CRM_API.Models.Payment", "FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");
                });

            modelBuilder.Entity("DriveFlow_CRM_API.Models.Request", b =>
                {
                    b.HasOne("DriveFlow_CRM_API.Models.AutoSchool", "AutoSchool")
                        .WithMany("Requests")
                        .HasForeignKey("AutoSchoolId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("AutoSchool");
                });

            modelBuilder.Entity("DriveFlow_CRM_API.Models.SessionForm", b =>
                {
                    b.HasOne("DriveFlow_CRM_API.Models.Appointment", "Appointment")
                        .WithOne()
                        .HasForeignKey("DriveFlow_CRM_API.Models.SessionForm", "AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DriveFlow_CRM_API.Models.ExamForm", "ExamForm")
                        .WithMany()
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("ExamForm");
                });

            modelBuilder.Entity("DriveFlow_CRM_API.Models.TeachingCategory", b =>
                {
                    b.HasOne("DriveFlow_CRM_API.Models.AutoSchool", "AutoSchool")
                        .WithMany("TeachingCategories")
                        .HasForeignKey("AutoSchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DriveFlow_CRM_API.Models.License", "License")
                        .WithMany("TeachingCategories")
                        .HasForeignKey("LicenseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AutoSchool");

                    b.Navigation("License");
                });

            modelBuilder.Entity("DriveFlow_CRM_API.Models.Vehicle", b =>
                {
                    b.HasOne("DriveFlow_CRM_API.Models.AutoSchool", "AutoSchool")
                        .WithMany("Vehicles")
                        .HasForeignKey("AutoSchoolId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DriveFlow_CRM_API.Models.License", "License")
                        .WithMany("Vehicles")
                        .HasForeignKey("LicenseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AutoSchool");

                    b.Navigation("License");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DriveFlow_CRM_API.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DriveFlow_CRM_API.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DriveFlow_CRM_API.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DriveFlow_CRM_API.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DriveFlow_CRM_API.Models.ApplicationUser", b =>
                {
                    b.Navigation("ApplicationUserTeachingCategories");

                    b.Navigation("InstructorAvailabilities");

                    b.Navigation("InstructorFiles");

                    b.Navigation("StudentFiles");
                });

            modelBuilder.Entity("DriveFlow_CRM_API.Models.AutoSchool", b =>
                {
                    b.Navigation("ApplicationUsers");

                    b.Navigation("Requests");

                    b.Navigation("TeachingCategories");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("DriveFlow_CRM_API.Models.City", b =>
                {
                    b.Navigation("Addresses");
                });

            modelBuilder.Entity("DriveFlow_CRM_API.Models.County", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("DriveFlow_CRM_API.Models.ExamForm", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("DriveFlow_CRM_API.Models.File", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("DriveFlow_CRM_API.Models.License", b =>
                {
                    b.Navigation("ExamForm");

                    b.Navigation("TeachingCategories");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("DriveFlow_CRM_API.Models.TeachingCategory", b =>
                {
                    b.Navigation("ApplicationUserTeachingCategories");

                    b.Navigation("Files");
                });

            modelBuilder.Entity("DriveFlow_CRM_API.Models.Vehicle", b =>
                {
                    b.Navigation("Files");
                });
#pragma warning restore 612, 618
        }
    }
}
